language: php

dist: xenial

services:
  - mysql

env:
  global:
    - COMPOSER_ROOT_VERSION="2.6.x-dev" DB=MYSQL

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer require --no-update silverstripe/versioned:1.6.x-dev
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

  - composer global require silverstripe/cow ^2
  - ~/.config/composer/vendor/bin/cow schema:validate

script:
  - vendor/bin/phpunit --testsuite cwp-recipe-core
